import { test, expect } from '@playwright/test'
import { mockApi, login } from './fixtures'

test('login, profile, skill filters, history, trajectory, logout', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const requests = await mockApi(page)
  await page.goto('/')
  await login(page, 'wrong-password')
  await expect(page.getByRole('alert')).toContainText('Неверный логин или пароль')
  await login(page)
  await expect(page.getByRole('heading', { name: 'Alex Test' })).toBeVisible()
  await expect(page.getByText('Критические дефициты', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Мои навыки', exact: true }).click()
  await page.getByLabel('Поиск навыков').fill('API')
  await expect(page.getByRole('heading', { name: 'API Design', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Teamwork', exact: true })).toHaveCount(0)
  await page.getByLabel('Поиск навыков').fill('')
  await page.getByRole('button', { name: 'Soft skills', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Teamwork', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'API Design', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'История обучения', exact: true }).click()
  await expect(page.getByRole('cell', { name: '0 / 100', exact: true })).toBeVisible()
  await page.getByLabel('Статус обучения').selectOption('completed')
  await expect(page.getByText('Architecture Fundamentals', { exact: true })).toBeVisible()
  await expect(page.getByText('Team Workshop', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Моя траектория', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Middle', exact: true })).toBeVisible()
  await expect(page.getByText('Общий процент готовности ещё не рассчитан.', { exact: false })).toBeVisible()
  expect(await page.evaluate(() => ({ local: localStorage.length, session: sessionStorage.length }))).toEqual({ local: 0, session: 0 })
  expect(requests.some(path => path === '/employees' || path.includes('/hr/'))).toBe(false)
  await page.getByRole('button', { name: 'Выйти', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Рады видеть вас' })).toBeVisible()
  expect(requests).toContain('/auth/logout')
  expect(errors).toEqual([])
})

test('missing goal and empty history have explanatory states', async ({ page }) => {
  await mockApi(page, { noGoal: true, emptyHistory: true })
  await page.goto('/'); await login(page)
  await page.getByRole('button', { name: 'Моя траектория', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Карьерная цель пока не задана' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Middle', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'История обучения', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Обучение ещё впереди' })).toBeVisible()
})

test('failed load is recoverable and unauthorized refresh clears data', async ({ page }) => {
  await mockApi(page, { failFirst: true })
  await page.goto('/'); await login(page)
  await expect(page.getByRole('alert')).toContainText('Не удалось обновить данные')
  await page.getByRole('button', { name: 'Повторить', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Alex Test' })).toBeVisible()
  await page.route('**/api/v1/employees/E_TEST', route => route.fulfill({ status: 401, json: {} }))
  await page.getByRole('button', { name: 'Обновить данные' }).click()
  await expect(page.getByRole('heading', { name: 'Рады видеть вас' })).toBeVisible()
  await expect(page.getByRole('status')).toContainText('Сессия завершена')
  await expect(page.getByRole('heading', { name: 'Alex Test' })).toHaveCount(0)
})

test('HR without personal profile never loads an employee dashboard', async ({ page }) => {
  const requests = await mockApi(page, { hr: true })
  await page.goto('/'); await login(page)
  await expect(page.getByRole('heading', { name: 'У этой учётной записи нет личного профиля' })).toBeVisible()
  expect(requests.filter(path => path.startsWith('/employees'))).toEqual([])
})

test('mobile navigation works without page overflow', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await mockApi(page)
  await page.goto('/'); await login(page)
  await expect(page.getByRole('heading', { name: 'Alex Test' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Открыть меню' }).click()
  await page.getByRole('button', { name: 'Мои навыки', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Навыки и требования' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
