import { useMemo, useState } from 'react'
import { ArrowRight, ArrowUpRight, Award, CalendarDays, Check, CheckCircle2, ChevronRight, CircleAlert, Clock3, Flag, Layers3, MapPin, Route, Search, Target } from 'lucide-react'
import type { Tab } from './App'
import type { DashboardData, HistoryRecord, HistoryStatus, Requirement, SkillType } from './types'

export function initials(name: string) { return name.trim().split(/\s+/).slice(0, 2).map(s => s[0]).join('').toUpperCase() }
export function dateLabel(date: string, short = false) {
  return new Intl.DateTimeFormat('ru-RU', { day: 'numeric', month: short ? 'short' : 'long', ...(short ? {} : { year: 'numeric' }), timeZone: 'UTC' }).format(new Date(`${date.slice(0, 10)}T12:00:00Z`))
}
const statusLabels: Record<HistoryStatus, string> = { completed: 'Завершено', in_progress: 'В процессе', dropped: 'Прекращено', no_show: 'Пропущено', declined: 'Отклонено', overdue: 'Просрочено' }
const formatLabels = { online: 'Онлайн', offline: 'Очно', self_paced: 'В своём темпе' }
const workFormats = { office: 'В офисе', hybrid: 'Гибридный формат', remote: 'Удалённо' }
const levelLabels = ['Нет оценки / уровень 0', 'Базовое понимание', 'Рабочие знания', 'Самостоятельная работа', 'Продвинутый уровень', 'Экспертный уровень']
const skillTypes: Record<SkillType, string> = { hard: 'Профессиональный', soft: 'Гибкий' }
function HistoryStatusBadge({ status }: { status: HistoryStatus }) { return <span className={`status-badge ${status}`}>{status === 'completed' && <Check size={12} />}{statusLabels[status]}</span> }
function BasisNote({ data }: { data: DashboardData }) {
  return <div className="basis-note"><CircleAlert size={16} /><p>{data.trajectory.skills_basis === 'last_review' ? <>Навыки по оценке от <strong>{dateLabel(data.trajectory.assessed_on)}</strong>. Обучение после этой даты ещё не учтено.</> : <>Навыки с учётом завершённого обучения на <strong>{dateLabel(data.trajectory.as_of_date)}</strong>. Если дата завершения неизвестна, использована дата записи истории.</>}</p></div>
}
function NoGoal({ unavailable = false }: { unavailable?: boolean }) {
  return <div className="empty-state"><span className="small-icon"><Target size={24} /></span><h3>{unavailable ? 'Требования пока недоступны' : 'Карьерная цель пока не задана'}</h3><p>{unavailable ? 'Для выбранной роли и грейда нет требований в каталоге. Уточните их у HR.' : 'Обсудите следующую роль и грейд с руководителем или HR. После добавления цели в профиль здесь появится ваша траектория.'}</p></div>
}
function LevelBar({ level, target }: { level: number; target?: number }) {
  return <div className="level-bar" role="img" aria-label={`Уровень ${level} из 5${target !== undefined ? `, требуется ${target}` : ''}`}>{[1, 2, 3, 4, 5].map(n => <span key={n} className={`${n <= level ? 'filled' : ''} ${n === target ? 'target-level' : ''}`} />)}</div>
}
function GapItem({ row }: { row: Requirement }) {
  return <div className="gap-item"><div className={`skill-symbol ${row.type}`}><Layers3 size={18} /></div><div className="gap-content"><div className="gap-title"><strong>{row.name}</strong>{row.critical && <span className="critical-tag">Критический</span>}</div><div className="gap-detail"><span>Сейчас {row.current_level}</span><ArrowRight size={12} /><span>Для цели {row.required_level}</span></div></div><span className="gap-number">+{row.gap}<small>ур.</small></span></div>
}
function RecentHistory({ data }: { data: DashboardData }) {
  const events = new Map(data.events.map(event => [event.event_id, event]))
  const recent = [...data.history].sort((a, b) => b.date.localeCompare(a.date) || b.record_id.localeCompare(a.record_id)).slice(0, 3)
  if (!recent.length) return <div className="empty-state"><CalendarDays size={27} /><h3>История начинается здесь</h3><p>После участия в обучении здесь появятся первые записи.</p></div>
  return <div className="recent-list">{recent.map(row => <div className="recent-item" key={row.record_id}><div className={`history-mark ${row.status}`} aria-hidden="true">{row.status === 'completed' ? <Check size={16} /> : <Clock3 size={16} />}</div><div><strong>{events.get(row.event_id)?.title ?? row.event_id}</strong><span>{dateLabel(row.date, true)} · {statusLabels[row.status]}</span></div><ChevronRight size={16} className="muted-icon" /></div>)}</div>
}

export function Overview({ data, navigate }: { data: DashboardData; navigate: (tab: Tab) => void }) {
  const { profile, trajectory } = data
  const gaps = trajectory.requirements.filter(row => row.gap > 0)
  const completed = data.history.filter(row => row.status === 'completed').length
  const target = trajectory.target
  return <>
    <div className="overview-hero-grid"><section className="hero-card"><div className="hero-content"><span className="hero-kicker"><span className="live-dot" />ЛИЧНЫЙ МАРШРУТ</span><h2>{profile.full_name.split(' ')[0]},<br />{target ? <>ваша цель —<br /><span>{target.target_grade}.</span></> : <>у каждого роста<br /><span>есть начало.</span></>}</h2><p>{target ? `Двигайтесь к роли ${target.target_role}, опираясь на свои сильные стороны.` : 'Познакомьтесь со своими навыками и выберите направление развития вместе с руководителем.'}</p><button className="button hero-button" onClick={() => navigate('trajectory')}>Посмотреть траекторию<ArrowUpRight size={17} /></button></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="orbit orbit-three" /><div className="orbit-axis" /><span className="orbit-point start"><span /><small>{profile.grade}</small></span><span className="orbit-point finish"><ArrowUpRight size={27} /><small>{target?.target_grade ?? 'Ваша цель'}</small></span><span className="art-spark one" /><span className="art-spark two" /></div></section>
      <section className="profile-card card"><div className="profile-top"><span className="avatar profile-avatar">{initials(profile.full_name)}</span><span className="pill">{profile.grade}</span></div><h2>{profile.full_name}</h2><p className="profile-role">{profile.role}</p><div className="profile-meta"><div><MapPin size={15} /><span>{profile.department}</span></div><div><CalendarDays size={15} /><span>В команде с {dateLabel(profile.hire_date, true)} {profile.hire_date.slice(0, 4)}</span></div><div><Layers3 size={15} /><span>{workFormats[profile.work_format]}</span></div></div><div className="profile-id"><span>Профиль сотрудника</span><strong>{profile.employee_id}</strong></div></section></div>
    <div className="stats-grid"><div className="stat-card"><span className="stat-icon green"><Target size={21} /></span><div><span className="stat-label">Требования цели</span><div className="stat-value">{trajectory.status === 'target_set' ? <>{trajectory.met_count}<small> / {trajectory.requirements.length}</small></> : '—'}</div><span className="stat-caption">{trajectory.status === 'target_set' ? 'навыков соответствуют требованиям' : 'появятся после выбора цели'}</span></div></div><div className="stat-card"><span className="stat-icon amber"><Flag size={21} /></span><div><span className="stat-label">Критические дефициты</span><div className="stat-value">{trajectory.status === 'target_set' ? trajectory.critical_gap_count : '—'}</div><span className="stat-caption">{trajectory.critical_gap_count ? 'приоритет для развития' : trajectory.status === 'target_set' ? 'все требования закрыты' : 'зависят от карьерной цели'}</span></div></div><div className="stat-card"><span className="stat-icon blue"><Award size={22} /></span><div><span className="stat-label">Завершённое обучение</span><div className="stat-value">{completed}</div><span className="stat-caption">записей о завершении в истории</span></div></div></div>
    <div className="next-step-banner"><div><strong>От навыков — к следующему шагу</strong><p>Подберите обучение и посмотрите прогноз результата.</p></div><button className="button primary" onClick={() => navigate('recommendations')}>К рекомендациям<ArrowRight size={17} /></button></div>
    <BasisNote data={data} />
    <div className="overview-lower-grid"><section className="card"><div className="section-heading"><div><span className="eyebrow">ФОКУС НА ГЛАВНОМ</span><h2>Зоны роста</h2></div><button className="text-button" onClick={() => navigate('skills')}>Все навыки<ArrowUpRight size={15} /></button></div>{trajectory.status !== 'target_set' ? <NoGoal unavailable={trajectory.status === 'target_unavailable'} /> : gaps.length ? <div className="gap-list">{gaps.slice(0, 3).map(row => <GapItem key={row.skill_id} row={row} />)}</div> : <div className="empty-state"><CheckCircle2 size={29} /><h3>Требования навыков выполнены</h3><p>Обсудите следующий шаг с руководителем. Соответствие навыков не означает автоматического повышения.</p></div>}<div className="card-footnote"><span className="tiny-dot" />Критические навыки — обязательные требования к цели.</div></section>
      <section className="card"><div className="section-heading"><div><span className="eyebrow">ВАШ ОПЫТ</span><h2>Недавнее обучение</h2></div><button className="text-button" onClick={() => navigate('history')} aria-label="Вся история обучения">Вся история<ArrowUpRight size={15} /></button></div><RecentHistory data={data} /><button className="card-footer-link" onClick={() => navigate('history')}>Посмотреть историю обучения<ArrowRight size={16} /></button></section></div>
  </>
}

export function SkillsView({ data }: { data: DashboardData }) {
  const [query, setQuery] = useState('')
  const [type, setType] = useState<'all' | SkillType>('all')
  const [scope, setScope] = useState<'all' | 'target'>('target')
  const { trajectory, profile } = data
  const hasTarget = trajectory.status === 'target_set'
  const requirements = new Map(trajectory.requirements.map(row => [row.skill_id, row]))
  const rows = data.catalog.skills.filter(skill => {
    const matchQuery = `${skill.name} ${skill.skill_id}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())
    return matchQuery && (type === 'all' || skill.type === type) && (!hasTarget || scope === 'all' || requirements.has(skill.skill_id))
  }).sort((a, b) => {
    const ra = requirements.get(a.skill_id), rb = requirements.get(b.skill_id)
    return Number(Boolean(rb?.critical && rb.gap)) - Number(Boolean(ra?.critical && ra.gap)) || a.name.localeCompare(b.name)
  })
  return <><BasisNote data={data} /><section className="card skills-card"><div className="section-heading"><div><span className="eyebrow">КАРТА КОМПЕТЕНЦИЙ</span><h2>Навыки и требования</h2></div><span className="pill neutral">Шкала 0–5</span></div>
    <div className="filter-toolbar"><label className="search-field"><Search size={17} /><input aria-label="Поиск навыков" value={query} onChange={e => setQuery(e.target.value)} placeholder="Найти навык…" /></label><div className="segmented" aria-label="Тип навыка">{(['all', 'hard', 'soft'] as const).map(value => <button key={value} aria-pressed={type === value} className={type === value ? 'selected' : ''} onClick={() => setType(value)}>{value === 'all' ? 'Все' : value === 'hard' ? 'Hard skills' : 'Soft skills'}</button>)}</div></div>
    <div className="skills-scope"><span>Найдено: {rows.length}</span>{hasTarget && <label><input type="checkbox" checked={scope === 'target'} onChange={e => setScope(e.target.checked ? 'target' : 'all')} />Только требования цели</label>}</div>
    {!hasTarget && <div className="inline-note">{trajectory.status === 'no_goal' ? 'Цель пока не задана. Показаны навыки из каталога без сравнения с требованиями.' : 'Требования цели не найдены. Показаны навыки из каталога.'}</div>}
    <div className="skill-grid">{rows.map(skill => {
      const row = requirements.get(skill.skill_id)
      const level = row?.current_level ?? trajectory.current_skills?.[skill.skill_id] ?? profile.skills[skill.skill_id] ?? 0
      return <article className={`skill-card ${row?.critical && row.gap ? 'needs-focus' : ''}`} key={skill.skill_id}><div className="skill-card-top"><span className={`skill-type ${skill.type}`}>{skill.type === 'hard' ? 'HARD SKILL' : 'SOFT SKILL'}</span>{row?.critical && <span className="critical-tag">Критический</span>}</div><h3>{skill.name}</h3><p className="skill-description">{skill.description}</p><div className="skill-level-caption"><span>{levelLabels[level]}</span><strong>{level}<small> / 5</small></strong></div><LevelBar level={level} target={row?.required_level} /><div className="skill-target-line">{row ? <><span>Требуется: <strong>{row.required_level}</strong></span><span className={row.gap ? 'gap-label' : 'met-label'}>{row.gap ? `Развить на ${row.gap} ур.` : <><Check size={13} />Соответствует</>}</span></> : <span>Не входит в требования цели</span>}</div></article>
    })}</div>{!rows.length && <div className="empty-state"><Search size={28} /><h3>Навыки не найдены</h3><p>Попробуйте другое название или измените фильтр.</p><button className="text-button" onClick={() => { setQuery(''); setType('all'); setScope('all') }}>Сбросить фильтры<ArrowRight size={15} /></button></div>}<div className="card-footnote">Если навык отсутствует в оценке и завершённом обучении, показан уровень 0. Метка на шкале обозначает требуемый уровень.</div></section></>
}

export function HistoryView({ data }: { data: DashboardData }) {
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState<HistoryStatus | 'all'>('all')
  const events = useMemo(() => new Map(data.events.map(event => [event.event_id, event])), [data.events])
  const rows = [...data.history].filter(row => (status === 'all' || row.status === status) && `${events.get(row.event_id)?.title ?? ''} ${row.event_id}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())).sort((a, b) => b.date.localeCompare(a.date) || b.record_id.localeCompare(a.record_id))
  const completed = data.history.filter(row => row.status === 'completed').length
  function details(row: HistoryRecord) {
    const event = events.get(row.event_id)
    return <><div className="history-event"><span className="history-event-icon"><CalendarDays size={18} /></span><div><strong>{event?.title ?? row.event_id}</strong><span>{event ? `${formatLabels[event.format]} · ${event.duration_hours} ч` : row.event_id}{event?.mandatory ? ' · Обязательное' : ''}</span></div></div></>
  }
  return <><div className="history-summary"><div><strong>{data.history.length}</strong><span>записей в истории</span></div><div><strong>{completed}</strong><span>завершено</span></div><div><strong>{data.history.filter(row => row.status === 'in_progress').length}</strong><span>в процессе</span></div></div><section className="card"><div className="section-heading"><div><span className="eyebrow">ШАГ ЗА ШАГОМ</span><h2>История вашего обучения</h2></div></div><div className="filter-toolbar"><label className="search-field"><Search size={17} /><input aria-label="Поиск обучения" value={query} onChange={e => setQuery(e.target.value)} placeholder="Найти мероприятие…" /></label><select aria-label="Статус обучения" value={status} onChange={e => setStatus(e.target.value as HistoryStatus | 'all')}><option value="all">Все статусы</option>{Object.entries(statusLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></div><div className="table-scroll"><table className="history-table"><caption className="sr-only">История участия в обучении</caption><thead><tr><th>Мероприятие</th><th>Дата</th><th>Статус</th><th>Выполнено</th><th>Оценка</th></tr></thead><tbody>{rows.map(row => <tr key={row.record_id}><td>{details(row)}</td><td className="date-cell">{dateLabel(row.date, true)}<small>{row.date.slice(0, 4)}</small></td><td><HistoryStatusBadge status={row.status} /></td><td>{row.completion_pct}%</td><td>{row.score === null ? <span className="muted">—</span> : `${row.score} / 100`}</td></tr>)}</tbody></table></div>{!rows.length && <div className="empty-state"><CalendarDays size={29} /><h3>{data.history.length ? 'По вашему запросу ничего не найдено' : 'Обучение ещё впереди'}</h3><p>{data.history.length ? 'Измените поиск или выберите другой статус.' : 'Здесь появятся ваши мероприятия и результаты участия.'}</p></div>}<div className="card-footnote">{rows.length} записей · Для обучения в своём темпе указана дата зачисления, а не завершения. Прочерк означает отсутствие оценки.</div></section></>
}

export function TrajectoryView({ data, navigate }: { data: DashboardData; navigate: (tab: Tab) => void }) {
  const { profile, trajectory } = data
  const target = trajectory.target
  const gaps = trajectory.requirements.filter(row => row.gap > 0)
  const critical = gaps.filter(row => row.critical)
  const sameRole = target?.target_role === profile.role
  return <><BasisNote data={data} /><section className="card trajectory-card"><div className="section-heading"><div><span className="eyebrow">НАПРАВЛЕНИЕ РАЗВИТИЯ</span><h2>Ваша карьерная траектория</h2></div><span className="small-icon"><Route size={24} /></span></div>{trajectory.status !== 'target_set' || !target ? <NoGoal unavailable={trajectory.status === 'target_unavailable'} /> : <>
    <div className="trajectory-path"><div className="path-step current"><span className="path-number"><MapPin size={21} /></span><span className="eyebrow">ВЫ ЗДЕСЬ</span><h3>{profile.grade}</h3><p>{profile.role}</p><span className="pill neutral">Текущая роль</span></div><div className="path-connector"><span /><ArrowRight size={20} /><span /></div><div className="path-step learning"><span className="path-number"><Layers3 size={21} /></span><span className="eyebrow">В ФОКУСЕ</span><h3>{gaps.length ? `${gaps.length} навыков` : 'Обсуждение цели'}</h3><p>{gaps.length ? 'для развития к цели' : 'Требования навыков выполнены'}</p><button className="text-button" onClick={() => navigate('skills')}>Посмотреть навыки<ArrowUpRight size={14} /></button></div><div className="path-connector"><span /><ArrowRight size={20} /><span /></div><div className="path-step goal"><span className="path-number"><Flag size={21} /></span><span className="eyebrow">ВАША ЦЕЛЬ</span><h3>{target.target_grade}</h3><p>{target.target_role}</p><span className="pill">{sameRole ? 'Развитие в роли' : 'Переход в другую роль'}</span></div></div>
    <div className="trajectory-disclaimer"><CircleAlert size={17} /><p>Это ориентир по требованиям навыков. Соответствие требованиям не гарантирует повышение — следующий шаг обсуждается с руководителем.</p></div></>}</section>
    {trajectory.status === 'target_set' && <><div className="trajectory-details-grid"><section className="card"><div className="section-heading"><div><span className="eyebrow">ОБЯЗАТЕЛЬНЫЙ МИНИМУМ</span><h2>Критические дефициты</h2></div><span className="count-badge">{critical.length}</span></div>{critical.length ? <div className="gap-list">{critical.map(row => <GapItem row={row} key={row.skill_id} />)}</div> : <div className="empty-state"><CheckCircle2 size={30} /><h3>Критические требования закрыты</h3><p>Все обязательные навыки соответствуют цели по текущему расчёту.</p></div>}</section><section className="card readiness-card"><span className="small-icon"><Target size={24} /></span><span className="eyebrow">СРАВНЕНИЕ С ЦЕЛЬЮ</span><h2>{trajectory.met_count}<small> из {trajectory.requirements.length}</small></h2><p>навыков соответствуют требованиям</p><div className="readiness-note">{trajectory.progress_pct === null ? 'Общий процент готовности ещё не рассчитан. Здесь показано сравнение отдельных навыков.' : `Готовность по расчёту движка: ${trajectory.progress_pct}%`}</div></section></div><section className="card"><div className="section-heading"><div><span className="eyebrow">ПРОЗРАЧНЫЕ ОРИЕНТИРЫ</span><h2>Все требования цели</h2></div><button className="text-button" onClick={() => navigate('skills')}>К карте навыков<ArrowUpRight size={15} /></button></div><div className="table-scroll"><table className="requirements-table"><caption className="sr-only">Требования карьерной цели</caption><thead><tr><th>Навык</th><th>Сейчас</th><th>Для цели</th><th>Результат сравнения</th></tr></thead><tbody>{trajectory.requirements.map(row => <tr key={row.skill_id}><td><strong>{row.name}</strong><small>{skillTypes[row.type]}{row.critical ? ' · Критический' : ''}</small></td><td>{row.current_level}</td><td>{row.required_level}</td><td>{row.gap ? <span className="gap-label">Развить на {row.gap} ур.</span> : <span className="met-label"><Check size={14} />Соответствует</span>}</td></tr>)}</tbody></table></div></section></>}
  </>
}
